import React, { useState, useRef, useEffect, useMemo } from 'react';
import { useStore } from '../../store/useStore';
import { useGraphStore } from '../../store/graphStore';
import { useDialogStore } from '../../store/dialogStore';
import { GitHubModal } from '../GitHubModal';
import { getScoreBadgeMarkdown, getScoreBadgeHtml, generateScoreBadgeSvg } from '../../utils/badge';
import { calculateHealthScore } from '../../utils/healthScore';
import type { Service, UserConfig, ServiceCategory, FlowEdge, HtmlExportData } from '../../types';

function generateServicesMd(services: Service[], projectName: string): string {
  const date = new Date().toISOString().split('T')[0];
  const byCategory = new Map<ServiceCategory, Service[]>();
  for (const s of services) {
    const list = byCategory.get(s.category) ?? [];
    list.push(s);
    byCategory.set(s.category, list);
  }

  const categoryLabels: Record<string, string> = {
    hosting: 'Hosting', database: 'Database', auth: 'Auth', payments: 'Payments',
    email: 'Email', analytics: 'Analytics', monitoring: 'Monitoring', cdn: 'CDN',
    storage: 'Storage', cicd: 'CI/CD', infra: 'Infrastructure', ai: 'AI',
    messaging: 'Messaging', domain: 'Domain', mobile: 'Mobile', gaming: 'Gaming',
    data: 'Data', support: 'Support', other: 'Other',
  };

  let md = `# Services — ${projectName}\n\nGenerated by StackWatch on ${date}\n`;
  for (const [cat, list] of byCategory) {
    md += `\n## ${categoryLabels[cat] ?? cat}\n`;
    md += '| Service | Plan | Cost | Renewal |\n';
    md += '|---|---|---|---|\n';
    for (const s of list) {
      const cost = s.cost ? `${s.cost.currency} ${s.cost.amount}/${s.cost.period}` : '\u2014';
      const renewal = s.renewalDate ?? '\u2014';
      md += `| ${s.name} | ${s.plan === 'unknown' ? '\u2014' : s.plan} | ${cost} | ${renewal} |\n`;
    }
  }

  const inferred = services.filter(s => s.source === 'inferred').length;
  const manual = services.filter(s => s.source === 'manual').length;
  md += `\n---\n*${inferred} services detected automatically`;
  if (manual > 0) md += ` \u00b7 ${manual} added manually`;
  md += '*\n';
  return md;
}

export const TopBar: React.FC = () => {
  const {
    repoPath,
    services,
    dependencies,
    config,
    isAnalyzing,
    analysisPhase,
    aiSettings,
    linkStatus,
    openFolder,
    analyzeLocal,
    analyzeGitHub,
    reanalyze,
    checkLinkStatus,
    relinkLocal,
    saveConfig,
    importStandalone,
    error,
    clearError,
  } = useStore();

  const { confirm } = useDialogStore();
  const graphNodes = useGraphStore(s => s.nodes);
  const graphEdges = useGraphStore(s => s.edges);

  const stackScore = useMemo(() => {
    if (services.length === 0) return 0;
    const fNodes = graphNodes.map(n => ({
      id: n.id, label: n.data.label, type: n.data.nodeType ?? 'external' as const, serviceId: n.data.serviceId,
    }));
    const fEdges = graphEdges.map(e => ({
      source: e.source, target: e.target, flowType: (e.data?.flowType as FlowEdge['flowType']) ?? 'data',
    }));
    return calculateHealthScore(services, fNodes, fEdges).score;
  }, [services, graphNodes, graphEdges]);

  const [showGitHub, setShowGitHub] = useState(false);
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [shareCopied, setShareCopied] = useState<string | null>(null);
  const exportMenuRef = useRef<HTMLDivElement>(null);
  const shareMenuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClick = (e: MouseEvent) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(e.target as Node)) {
        setShowExportMenu(false);
      }
      if (shareMenuRef.current && !shareMenuRef.current.contains(e.target as Node)) {
        setShowShareMenu(false);
        setShareCopied(null);
      }
    };
    if (showExportMenu || showShareMenu) document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
  }, [showExportMenu, showShareMenu]);

  // Check link status when config changes
  useEffect(() => {
    if (config) checkLinkStatus();
  }, [config, checkLinkStatus]);

  const handleReanalyze = async () => {
    if (!repoPath) return;
    if (repoPath.startsWith('github:')) {
      setShowGitHub(true);
    } else {
      await reanalyze();
    }
  };

  const handleImport = async () => {
    // Import always loads a JSON file into memory — no disk writes, no overwrites.
    // User picks any .json file, state is restored from it.
    await importStandalone();
  };

  const handleExportConfig = async () => {
    if (!window.stackwatch) return;
    setShowExportMenu(false);
    const exportConfig: UserConfig = config ?? {
      version: '1',
      project: { name: repoPath?.split(/[/\\]/).pop() ?? '', description: '' },
      services: services.filter(s => s.source === 'manual'),
      accounts: [],
    };
    const allServices = [...services];
    const fullConfig = { ...exportConfig, services: allServices };
    await window.stackwatch.exportConfig(JSON.stringify(fullConfig, null, 2));
  };

  const handleExportMd = async () => {
    if (!window.stackwatch) return;
    setShowExportMenu(false);
    const projectName = config?.project?.name || repoPath?.split(/[/\\]/).pop() || 'Project';
    const md = generateServicesMd(services, projectName);
    await window.stackwatch.exportServicesMd(md);
  };

  const handleExportHtml = async () => {
    if (!window.stackwatch) return;
    setShowExportMenu(false);
    const projectName = config?.project?.name || repoPath?.split(/[/\\]/).pop() || 'Project';
    const fNodes = graphNodes.map(n => ({
      id: n.id, label: n.data.label, type: n.data.nodeType ?? 'external' as const, serviceId: n.data.serviceId,
    }));
    const fEdges = graphEdges.map(e => ({
      source: e.source, target: e.target, label: e.data?.label, flowType: (e.data?.flowType as FlowEdge['flowType']) ?? 'data',
    }));
    const health = calculateHealthScore(services, fNodes, fEdges);
    const data: HtmlExportData = {
      projectName,
      services,
      dependencies,
      flowNodes: fNodes,
      flowEdges: fEdges,
      score: health.score,
      scoreBreakdown: {
        servicesWithCost: health.servicesWithCost,
        servicesWithOwner: health.servicesWithOwner,
        servicesReviewed: health.servicesReviewed,
        graphCompleteness: health.graphCompleteness,
      },
      generatedAt: new Date().toISOString(),
      budget: config?.budget ? { monthly: config.budget.monthly, currency: config.budget.currency } : undefined,
    };
    await window.stackwatch.exportHtml(data);
  };

  const handleShareCopy = (key: string, text: string) => {
    navigator.clipboard.writeText(text);
    setShareCopied(key);
    setTimeout(() => setShareCopied(null), 2000);
  };

  const getBadgeMarkdown = (): string => {
    return getScoreBadgeMarkdown(stackScore, services.length);
  };

  const getBadgeHtml = (): string => {
    return getScoreBadgeHtml(stackScore, services.length);
  };

  const getStackSummary = (): string => {
    const serviceCount = services.length;
    const depCount = dependencies.length;
    const monthlyCost = services.reduce((sum, s) => {
      if (!s.cost) return sum;
      const monthly = s.cost.period === 'yearly' ? s.cost.amount / 12 : s.cost.amount;
      return sum + monthly;
    }, 0);
    return `\u{1F50D} My project uses ${serviceCount} services, ${depCount} dependencies, ~$${Math.round(monthlyCost)}/mo\nStack Score: ${stackScore}/100\nAnalyzed with StackWatch`;
  };

  return (
    <div className="h-12 border-b flex items-center px-3 gap-2 shrink-0" style={{ background: 'var(--color-bg-secondary)', borderColor: 'var(--color-border)' }}>
      {/* Left zone — Import / Export */}
      <div className="flex items-center gap-1.5 shrink-0">
        <button
          onClick={handleImport}
          disabled={isAnalyzing}
          className="flex items-center gap-1.5 px-2.5 py-1 font-mono text-[11px] tracking-widest uppercase text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] disabled:opacity-40 disabled:cursor-not-allowed rounded-sm transition-colors"
          title="Import config — restore all services, graph layout, and edits from a previously exported file"
        >
          <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 4v12m0 0l-4-4m4 4l4-4M4 18h16" />
          </svg>
          Import
        </button>

        <div className="relative" ref={exportMenuRef}>
          <button
            onClick={() => setShowExportMenu(!showExportMenu)}
            disabled={services.length === 0 || isAnalyzing}
            className="flex items-center gap-1.5 px-2.5 py-1 font-mono text-[11px] tracking-widest uppercase text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] disabled:opacity-40 disabled:cursor-not-allowed rounded-sm transition-colors"
            title="Export — save config backup or generate report"
          >
            <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 20V8m0 0l4 4m-4-4l-4 4M4 6h16" />
            </svg>
            Export
          </button>

          {showExportMenu && (
            <div
              className="absolute top-full left-0 mt-1 border rounded-none shadow-lg z-50 min-w-[180px]"
              style={{ background: 'var(--color-bg-secondary)', borderColor: 'var(--color-border)' }}
              role="menu"
              onKeyDown={(e) => { if (e.key === 'Escape') setShowExportMenu(false); }}
            >
              <button
                onClick={handleExportConfig}
                className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors"
                role="menuitem"
              >
                Backup config (.json)
              </button>
              <button
                onClick={handleExportMd}
                className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors border-t border-[var(--color-border)]"
                role="menuitem"
              >
                Report (.md)
              </button>
              <button
                onClick={handleExportHtml}
                className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors border-t border-[var(--color-border)]"
                role="menuitem"
              >
                Dashboard (.html)
              </button>
            </div>
          )}
        </div>

        {services.length > 0 && (
          <div className="relative" ref={shareMenuRef}>
            <button
              onClick={() => setShowShareMenu(!showShareMenu)}
              disabled={isAnalyzing}
              className="flex items-center gap-1.5 px-2.5 py-1 font-mono text-[11px] tracking-widest uppercase text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] disabled:opacity-40 disabled:cursor-not-allowed rounded-sm transition-colors"
              title="Share — copy badge or stack summary"
            >
              <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M4 12v7a2 2 0 002 2h12a2 2 0 002-2v-7M16 6l-4-4-4 4M12 2v13" />
              </svg>
              Share
            </button>

            {showShareMenu && (
              <div
                className="absolute top-full left-0 mt-1 border rounded-none shadow-lg z-50 min-w-[220px]"
                style={{ background: 'var(--color-bg-secondary)', borderColor: 'var(--color-border)' }}
                role="menu"
                onKeyDown={(e) => { if (e.key === 'Escape') { setShowShareMenu(false); setShareCopied(null); } }}
              >
                <button
                  onClick={() => handleShareCopy('md', getBadgeMarkdown())}
                  className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors"
                  role="menuitem"
                >
                  {shareCopied === 'md' ? 'Copied!' : 'Copy Badge (Markdown)'}
                </button>
                <button
                  onClick={() => handleShareCopy('html', getBadgeHtml())}
                  className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors border-t border-[var(--color-border)]"
                  role="menuitem"
                >
                  {shareCopied === 'html' ? 'Copied!' : 'Copy Badge (HTML)'}
                </button>
                <button
                  onClick={() => handleShareCopy('summary', getStackSummary())}
                  className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors border-t border-[var(--color-border)]"
                  role="menuitem"
                >
                  {shareCopied === 'summary' ? 'Copied!' : 'Copy Stack Summary'}
                </button>
                <button
                  onClick={() => {
                    const svg = generateScoreBadgeSvg(stackScore, services.length);
                    handleShareCopy('svg', svg);
                  }}
                  className="w-full text-left px-3 py-2 text-xs text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-hover)] transition-colors border-t border-[var(--color-border)]"
                  role="menuitem"
                >
                  {shareCopied === 'svg' ? 'Copied!' : 'Copy Badge (SVG)'}
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Center zone — Repo path + link status */}
      <div className="flex items-center gap-1.5 min-w-0 flex-1 justify-center">
        <span className="text-[var(--color-text-muted)] text-sm shrink-0">
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
          </svg>
        </span>
        <span className={repoPath ? 'text-sm text-[var(--color-text-secondary)] truncate' : 'font-mono text-[11px] uppercase tracking-widest text-[var(--color-text-muted)] truncate'}>
          {repoPath ?? 'No repository loaded'}
        </span>
        {repoPath && (
          <div className="flex items-center gap-1.5 shrink-0">
            {linkStatus === 'linked' && (
              <span className="flex items-center gap-1 text-[11px] text-[#3d8c5e]">
                <span className="w-1.5 h-1.5 rounded-full bg-[#3d8c5e] inline-block" />
                Linked
              </span>
            )}
            {linkStatus === 'unlinked' && (
              <>
                <span className="flex items-center gap-1 text-[11px] text-[var(--color-accent)]">
                  <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-accent)] inline-block" />
                  Unlinked
                </span>
                <button
                  onClick={relinkLocal}
                  disabled={isAnalyzing}
                  className="text-[11px] text-[var(--color-accent)] hover:opacity-80 disabled:opacity-50 transition-colors"
                >
                  Re-link
                </button>
              </>
            )}
            {linkStatus === 'unknown' && (
              <span className="w-1.5 h-1.5 rounded-full bg-gray-500 inline-block" />
            )}
          </div>
        )}
      </div>

      {/* Error display */}
      {error && (
        <div className="flex items-center gap-2 bg-red-950/30 border border-red-900/50 rounded-sm px-3 py-1 shrink-0">
          <span className="text-red-400 text-xs truncate max-w-64">{error}</span>
          <button onClick={clearError} className="text-red-400 hover:text-red-300 text-xs">x</button>
        </div>
      )}

      {/* GitHub modal */}
      {showGitHub && (
        <GitHubModal
          onAnalyze={(repo, token) => {
            analyzeGitHub(repo, token);
            setShowGitHub(false);
          }}
          onClose={() => setShowGitHub(false)}
        />
      )}

      {/* Right zone — GitHub, Open Folder, Re-analyze */}
      <div className="flex items-center gap-1.5 shrink-0">
        <button
          onClick={() => setShowGitHub(!showGitHub)}
          className="p-1.5 text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] hover:bg-[var(--color-bg-hover)] rounded-sm transition-colors"
          title="Connect GitHub repo"
        >
          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
            <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z" />
          </svg>
        </button>

        <button
          onClick={openFolder}
          disabled={isAnalyzing}
          className="p-1.5 text-[var(--color-text-secondary)] hover:text-[var(--color-accent)] hover:bg-[var(--color-bg-hover)] disabled:opacity-50 rounded-sm transition-colors"
          title="Open folder"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
              d="M5 19a2 2 0 01-2-2V7a2 2 0 012-2h4l2 2h4a2 2 0 012 2v1M5 19h14a2 2 0 002-2v-5a2 2 0 00-2-2H9a2 2 0 00-2 2v5a2 2 0 01-2 2z" />
          </svg>
        </button>

        {repoPath && (
          <button
            onClick={handleReanalyze}
            disabled={isAnalyzing}
            className="px-3 py-1 font-mono text-[11px] uppercase tracking-widest text-[var(--color-text-secondary)] border border-[var(--color-border)] hover:text-[var(--color-accent)] hover:border-[var(--color-accent)] disabled:opacity-50 rounded-sm transition-colors"
          >
            {isAnalyzing ? (
              <span className="flex items-center gap-1.5">
                <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                {analysisPhase ?? 'Analyzing...'}
              </span>
            ) : (
              'Re-analyze'
            )}
          </button>
        )}
      </div>
    </div>
  );
};
