#!/usr/bin/env node

import path from 'path'
import fs from 'fs'
import { analyzeLocalRepo } from '../electron/analyzers/index'
import type { AnalysisResult } from '../shared/types'

const args = process.argv.slice(2)

// Parse flags
const flags = {
  json: args.includes('--json'),
  markdown: args.includes('--md') || args.includes('--markdown'),
  help: args.includes('--help') || args.includes('-h'),
  version: args.includes('--version') || args.includes('-v'),
}

// Get target path (first non-flag argument)
const targetPath = args.find(a => !a.startsWith('-')) || '.'

if (flags.version) {
  const pkg = JSON.parse(fs.readFileSync(path.join(__dirname, '..', '..', 'package.json'), 'utf-8'))
  console.log(`stackwatch v${pkg.version}`)
  process.exit(0)
}

if (flags.help) {
  console.log(`
  StackWatch CLI — scan your codebase and map every service

  Usage:
    npx stackwatch [path] [options]

  Arguments:
    path              Path to repository (default: current directory)

  Options:
    --json            Output as JSON
    --md, --markdown  Output as Markdown table
    -h, --help        Show this help
    -v, --version     Show version

  Examples:
    npx stackwatch                   # Scan current directory
    npx stackwatch ./my-project      # Scan specific path
    npx stackwatch --json            # JSON output for piping
    npx stackwatch --md > SERVICES.md  # Generate Markdown report
  `.trim())
  process.exit(0)
}

async function main() {
  const resolvedPath = path.resolve(targetPath)

  if (!fs.existsSync(resolvedPath)) {
    console.error(`Error: path "${resolvedPath}" does not exist`)
    process.exit(1)
  }

  if (!fs.statSync(resolvedPath).isDirectory()) {
    console.error(`Error: "${resolvedPath}" is not a directory`)
    process.exit(1)
  }

  const projectName = path.basename(resolvedPath)

  if (!flags.json && !flags.markdown) {
    console.log(`\n  STACKWATCH — scanning ${projectName}\n`)
  }

  try {
    const result = await analyzeLocalRepo(resolvedPath)

    if (flags.json) {
      console.log(JSON.stringify(result, null, 2))
    } else if (flags.markdown) {
      printMarkdown(result, projectName)
    } else {
      printSummary(result, projectName)
    }
  } catch (err) {
    console.error(`Error: ${err instanceof Error ? err.message : String(err)}`)
    process.exit(1)
  }
}

function printSummary(result: AnalysisResult, projectName: string) {
  const { services, dependencies } = result

  console.log(`  Project:      ${projectName}`)
  console.log(`  Services:     ${services.length}`)
  console.log(`  Dependencies: ${dependencies.length}`)
  console.log()

  if (services.length > 0) {
    // Group by category
    const byCategory = new Map<string, typeof services>()
    for (const s of services) {
      const list = byCategory.get(s.category) ?? []
      list.push(s)
      byCategory.set(s.category, list)
    }

    console.log('  SERVICES')
    console.log('  ' + '-'.repeat(60))
    for (const [category, svcs] of byCategory) {
      console.log(`  ${category.toUpperCase()} (${svcs.length})`)
      for (const s of svcs) {
        const conf = s.confidence === 'high' ? '●' : s.confidence === 'medium' ? '◐' : '○'
        console.log(`    ${conf} ${s.name}  [${s.plan}]`)
      }
    }
    console.log()
  }

  if (dependencies.length > 0) {
    const byEco = new Map<string, number>()
    for (const d of dependencies) {
      byEco.set(d.ecosystem, (byEco.get(d.ecosystem) ?? 0) + 1)
    }
    console.log('  DEPENDENCIES')
    console.log('  ' + '-'.repeat(60))
    for (const [eco, count] of byEco) {
      console.log(`    ${eco}: ${count}`)
    }
    console.log()
  }

  // Confidence breakdown
  const high = services.filter(s => s.confidence === 'high').length
  const med = services.filter(s => s.confidence === 'medium').length
  const low = services.filter(s => s.confidence === 'low').length
  if (services.length > 0) {
    console.log(`  Confidence: ${high} high, ${med} medium, ${low} low`)
  }
  console.log()
}

function printMarkdown(result: AnalysisResult, projectName: string) {
  const { services, dependencies } = result
  const date = new Date().toISOString().split('T')[0]

  console.log(`# Services — ${projectName}\n`)
  console.log(`Generated by StackWatch CLI on ${date}\n`)

  if (services.length > 0) {
    // Group by category
    const byCategory = new Map<string, typeof services>()
    for (const s of services) {
      const list = byCategory.get(s.category) ?? []
      list.push(s)
      byCategory.set(s.category, list)
    }

    for (const [category, svcs] of byCategory) {
      console.log(`## ${category.charAt(0).toUpperCase() + category.slice(1)}\n`)
      console.log('| Service | Plan | Confidence |')
      console.log('|---|---|---|')
      for (const s of svcs) {
        console.log(`| ${s.name} | ${s.plan} | ${s.confidence ?? 'medium'} |`)
      }
      console.log()
    }
  }

  if (dependencies.length > 0) {
    console.log(`## Dependencies (${dependencies.length})\n`)
    console.log('| Name | Version | Type | Ecosystem |')
    console.log('|---|---|---|---|')
    for (const d of dependencies) {
      console.log(`| ${d.name} | ${d.version} | ${d.type} | ${d.ecosystem} |`)
    }
    console.log()
  }

  console.log(`---\n*Generated by [StackWatch](https://github.com/alciller88/StackWatch)*`)
}

main()
