import type { Service, Dependency, FlowNode, FlowEdge } from './types';
import { DEFAULT_GRAPH_STYLES } from './styles/defaults';

export const demoServices: Service[] = [
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'hosting',
    plan: 'paid',
    source: 'inferred',
    confidence: 'high',
    confidenceReasons: ['Found in vercel.json config'],
    inferredFrom: 'vercel.json',
    billing: { type: 'automatic', period: 'monthly', amount: 20, currency: 'USD', nextDate: '2026-04-15' },
    owner: 'Frontend Team',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'database',
    plan: 'free',
    source: 'inferred',
    confidence: 'high',
    confidenceReasons: ['@supabase/supabase-js in package.json'],
    inferredFrom: 'package.json',
    url: 'https://app.supabase.com',
    owner: 'Backend Team',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'payments',
    plan: 'paid',
    source: 'inferred',
    confidence: 'high',
    confidenceReasons: ['stripe package in dependencies'],
    inferredFrom: 'package.json',
    billing: { type: 'automatic', period: 'usage-based', amount: 0, currency: 'USD' },
    notes: 'Pay-per-transaction model',
    owner: 'Payments Team',
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    category: 'cicd',
    plan: 'free',
    source: 'inferred',
    confidence: 'high',
    confidenceReasons: ['.github/workflows/ directory exists'],
    inferredFrom: '.github/workflows/ci.yml',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'cdn',
    plan: 'free',
    source: 'inferred',
    confidence: 'medium',
    confidenceReasons: ['DNS records suggest Cloudflare'],
    inferredFrom: 'DNS configuration',
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'monitoring',
    plan: 'paid',
    source: 'inferred',
    confidence: 'high',
    confidenceReasons: ['@sentry/nextjs in package.json'],
    inferredFrom: 'package.json',
    billing: { type: 'manual', period: 'monthly', amount: 26, currency: 'USD', nextDate: '2026-05-01', lastRenewed: '2026-04-01' },
    accountEmail: 'devops@example.com',
  },
];

export const demoDependencies: Dependency[] = [
  { name: 'next', version: '14.2.0', type: 'production', ecosystem: 'npm' },
  { name: 'react', version: '18.3.1', type: 'production', ecosystem: 'npm' },
  { name: 'typescript', version: '5.4.5', type: 'development', ecosystem: 'npm' },
  { name: '@supabase/supabase-js', version: '2.42.0', type: 'production', ecosystem: 'npm', relatedService: 'supabase' },
  { name: 'stripe', version: '15.0.0', type: 'production', ecosystem: 'npm', relatedService: 'stripe' },
  { name: '@sentry/nextjs', version: '7.105.0', type: 'production', ecosystem: 'npm', relatedService: 'sentry' },
  { name: 'tailwindcss', version: '3.4.3', type: 'development', ecosystem: 'npm' },
  { name: 'eslint', version: '8.57.0', type: 'development', ecosystem: 'npm' },
  { name: 'zustand', version: '4.5.2', type: 'production', ecosystem: 'npm' },
];

export const demoFlowNodes: FlowNode[] = [
  { id: 'user', label: 'User', type: 'layer', layerColor: DEFAULT_GRAPH_STYLES.layerColors.user },
  { id: 'svc-cloudflare', label: 'Cloudflare CDN', type: 'cdn', serviceId: 'cloudflare' },
  { id: 'frontend', label: 'Frontend', type: 'layer', layerColor: DEFAULT_GRAPH_STYLES.layerColors.frontend },
  { id: 'api', label: 'Backend', type: 'layer', layerColor: DEFAULT_GRAPH_STYLES.layerColors.backend },
  { id: 'svc-vercel', label: 'Vercel (Next.js)', type: 'external', serviceId: 'vercel' },
  { id: 'svc-supabase', label: 'Supabase DB', type: 'database', serviceId: 'supabase' },
  { id: 'svc-stripe', label: 'Stripe', type: 'external', serviceId: 'stripe' },
  { id: 'svc-sentry', label: 'Sentry', type: 'external', serviceId: 'sentry' },
];

export const demoFlowEdges: FlowEdge[] = [
  { source: 'user', target: 'frontend', flowType: 'data' },
  { source: 'user', target: 'svc-cloudflare', flowType: 'data' },
  { source: 'frontend', target: 'svc-vercel', flowType: 'data' },
  { source: 'frontend', target: 'api', flowType: 'data' },
  { source: 'api', target: 'svc-supabase', flowType: 'data' },
  { source: 'api', target: 'svc-stripe', flowType: 'payment' },
  { source: 'frontend', target: 'svc-sentry', flowType: 'data' },
];
