export const themes = {
  dark: {
    '--color-bg-primary': '#0a0c0f',
    '--color-bg-secondary': '#0d1017',
    '--color-bg-tertiary': '#111620',
    '--color-bg-hover': '#141a24',
    '--color-text-primary': '#dce1e8',
    '--color-text-secondary': '#8a9ab4',
    '--color-text-muted': '#8e9db6',
    '--color-accent': '#e2b04a',
    '--color-accent-hover': '#f0c060',
    '--color-border': '#1e2430',
    '--color-border-light': '#1a2130',
    '--color-grid': '#1a2130',
    // Semantic colors
    '--color-danger': '#c05050',
    '--color-danger-muted': '#5a2a2a',
    '--color-success': '#3d8c5e',
    '--color-success-muted': '#2a5a2a',
    '--color-warning': '#c4962e',
    '--color-badge-bg-warning': '#2a1e0a',
    '--color-badge-border-warning': '#6b3d0a',
    '--color-badge-bg-success': '#1a3a1a',
    '--color-badge-border-success': '#2a5a2a',
    '--color-badge-bg-danger': '#1a1520',
    '--color-badge-border-danger': '#4a2040',
    '--color-info': '#4a8ab0',
    '--color-info-bg': '#1a2a3a',
    '--color-info-border': '#2a4a6a',
    '--color-danger-bg': '#1a0a0a',
  },
  light: {
    '--color-bg-primary': '#f0f2f5',
    '--color-bg-secondary': '#e8eaed',
    '--color-bg-tertiary': '#dde0e6',
    '--color-bg-hover': '#d4d8e0',
    '--color-text-primary': '#1a1d23',
    '--color-text-secondary': '#4a5568',
    '--color-text-muted': '#5a6a7e',
    '--color-accent': '#c4962e',
    '--color-accent-hover': '#a87d25',
    '--color-border': '#d4d8e0',
    '--color-border-light': '#c8ccd4',
    '--color-grid': '#d4d8e0',
    // Semantic colors
    '--color-danger': '#c03030',
    '--color-danger-muted': '#e8d0d0',
    '--color-success': '#2a7048',
    '--color-success-muted': '#d0e8d8',
    '--color-warning': '#a87d25',
    '--color-badge-bg-warning': '#fef3d0',
    '--color-badge-border-warning': '#e0c060',
    '--color-badge-bg-success': '#d0f0d8',
    '--color-badge-border-success': '#60c080',
    '--color-badge-bg-danger': '#f8e0f0',
    '--color-badge-border-danger': '#c060a0',
    '--color-info': '#0369a1',
    '--color-info-bg': '#f0f9ff',
    '--color-info-border': '#bae6fd',
    '--color-danger-bg': '#fef2f2',
  },
} as const;

export type ThemeName = keyof typeof themes;
