export const themes = {
  dark: {
    '--color-bg-primary': '#0a0c0f',
    '--color-bg-secondary': '#0d1017',
    '--color-bg-tertiary': '#111620',
    '--color-bg-hover': '#141a24',
    '--color-text-primary': '#dce1e8',
    '--color-text-secondary': '#8a9ab4',
    '--color-text-muted': '#8e9db6',
    '--color-accent': '#e2b04a',
    '--color-accent-hover': '#f0c060',
    '--color-border': '#1e2430',
    '--color-border-light': '#1a2130',
    '--color-grid': '#1a2130',
    // Semantic colors
    '--color-danger': '#c05050',
    '--color-danger-muted': '#5a2a2a',
    '--color-success': '#3d8c5e',
    '--color-success-muted': '#2a5a2a',
    '--color-warning': '#c4962e',
    '--color-badge-bg-warning': '#2a1e0a',
    '--color-badge-border-warning': '#6b3d0a',
    '--color-badge-bg-success': '#1a3a1a',
    '--color-badge-border-success': '#2a5a2a',
    '--color-badge-bg-danger': '#1a1520',
    '--color-badge-border-danger': '#4a2040',
    '--color-info': '#4a8ab0',
    '--color-info-bg': '#1a2a3a',
    '--color-info-border': '#2a4a6a',
    '--color-danger-bg': '#1a0a0a',
  },
  light: {
    '--color-bg-primary': '#d8dbe2',
    '--color-bg-secondary': '#e4e7ec',
    '--color-bg-tertiary': '#cdd1da',
    '--color-bg-hover': '#c4c8d2',
    '--color-text-primary': '#141720',
    '--color-text-secondary': '#363e50',
    '--color-text-muted': '#4a5368',
    '--color-accent': '#a07820',
    '--color-accent-hover': '#886518',
    '--color-border': '#bcc0ca',
    '--color-border-light': '#b0b4be',
    '--color-grid': '#c4c8d2',
    // Semantic colors
    '--color-danger': '#b02828',
    '--color-danger-muted': '#e0c0c0',
    '--color-success': '#1e6040',
    '--color-success-muted': '#c0e0cc',
    '--color-warning': '#8a6818',
    '--color-badge-bg-warning': '#e8dbb0',
    '--color-badge-border-warning': '#c4a040',
    '--color-badge-bg-success': '#c0e0c8',
    '--color-badge-border-success': '#50a868',
    '--color-badge-bg-danger': '#e8c8dc',
    '--color-badge-border-danger': '#a85088',
    '--color-info': '#0a5a8a',
    '--color-info-bg': '#d0e4f0',
    '--color-info-border': '#80b8d8',
    '--color-danger-bg': '#e8d0d0',
  },
} as const;

export type ThemeName = keyof typeof themes;
